package com.hi.pay.models;

// Generated 2013-8-22 15:24:01 by Hibernate Tools 3.2.1.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCaterPayChannel generated by hbm2java
 */
@Entity
@Table(name = "T_CATER_PAY_CHANNEL")
public class TCaterPayChannel implements java.io.Serializable {

	private String channelNo;
	private String channelName;
	private transient String merchantNo;
	private transient String merchantKey;
	private transient String interface_;

	public TCaterPayChannel() {
	}

	public TCaterPayChannel(String channelNo) {
		this.channelNo = channelNo;
	}

	public TCaterPayChannel(String channelNo, String channelName,
			String merchantNo, String merchantKey, String interface_) {
		this.channelNo = channelNo;
		this.channelName = channelName;
		this.merchantNo = merchantNo;
		this.merchantKey = merchantKey;
		this.interface_ = interface_;
	}

	@Id
	@Column(name = "CHANNEL_NO", unique = true, nullable = false, length = 32)
	public String getChannelNo() {
		return this.channelNo;
	}

	public void setChannelNo(String channelNo) {
		this.channelNo = channelNo;
	}

	@Column(name = "CHANNEL_NAME", length = 32)
	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	@Column(name = "MERCHANT_NO", length = 62)
	public String getMerchantNo() {
		return this.merchantNo;
	}

	public void setMerchantNo(String merchantNo) {
		this.merchantNo = merchantNo;
	}

	@Column(name = "MERCHANT_KEY", length = 128)
	public String getMerchantKey() {
		return this.merchantKey;
	}

	public void setMerchantKey(String merchantKey) {
		this.merchantKey = merchantKey;
	}

	@Column(name = "INTERFACE", length = 32)
	public String getInterface_() {
		return this.interface_;
	}

	public void setInterface_(String interface_) {
		this.interface_ = interface_;
	}

}
