package com.hi.pay.models;

// Generated 2013-8-22 17:55:19 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCaterOrderexpensesinfo generated by hbm2java
 */
@Entity
@Table(name = "T_CATER_ORDEREXPENSESINFO")
public class TCaterOrderexpensesinfo implements java.io.Serializable {

	private BigDecimal id;
	private String deposit;
	private String waiterfee;
	private String deliveryfee;
	private BigDecimal dishprice;
	private BigDecimal totalprice;
	private String orderid;
	private String feememo;
	private String kilometre;

	public TCaterOrderexpensesinfo() {
	}

	public TCaterOrderexpensesinfo(BigDecimal id) {
		this.id = id;
	}

	public TCaterOrderexpensesinfo(BigDecimal id, String deposit,
			String waiterfee, String deliveryfee, BigDecimal dishprice,
			BigDecimal totalprice, String orderid, String feememo,
			String kilometre) {
		this.id = id;
		this.deposit = deposit;
		this.waiterfee = waiterfee;
		this.deliveryfee = deliveryfee;
		this.dishprice = dishprice;
		this.totalprice = totalprice;
		this.orderid = orderid;
		this.feememo = feememo;
		this.kilometre = kilometre;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "DEPOSIT", length = 16)
	public String getDeposit() {
		return this.deposit;
	}

	public void setDeposit(String deposit) {
		this.deposit = deposit;
	}

	@Column(name = "WAITERFEE", length = 16)
	public String getWaiterfee() {
		return this.waiterfee;
	}

	public void setWaiterfee(String waiterfee) {
		this.waiterfee = waiterfee;
	}

	@Column(name = "DELIVERYFEE", length = 16)
	public String getDeliveryfee() {
		return this.deliveryfee;
	}

	public void setDeliveryfee(String deliveryfee) {
		this.deliveryfee = deliveryfee;
	}

	@Column(name = "DISHPRICE", precision = 8)
	public BigDecimal getDishprice() {
		return this.dishprice;
	}

	public void setDishprice(BigDecimal dishprice) {
		this.dishprice = dishprice;
	}

	@Column(name = "TOTALPRICE", precision = 8)
	public BigDecimal getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(BigDecimal totalprice) {
		this.totalprice = totalprice;
	}

	@Column(name = "ORDERID", length = 32)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "FEEMEMO", length = 512)
	public String getFeememo() {
		return this.feememo;
	}

	public void setFeememo(String feememo) {
		this.feememo = feememo;
	}

	@Column(name = "KILOMETRE", length = 32)
	public String getKilometre() {
		return this.kilometre;
	}

	public void setKilometre(String kilometre) {
		this.kilometre = kilometre;
	}

}
