package com.hi.pay.models;

// Generated 2013-9-10 9:47:37 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TCaterThirdorderinfo generated by hbm2java
 */
@Entity
@Table(name = "T_CATER_THIRDORDERINFO")
public class TCaterThirdorderinfo implements java.io.Serializable {

	private Long id;
	private String orderId;
	private String thirdOrderId;
	private String refundNo;
	private String channelNo;
	private String channelName;
	private String payStatus;
	private String transactionId;
	private String bankType;
	private String bankBillno;
	private BigDecimal amount;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private String merchantNo;
	private String payStoreId;
	private String payStoreName;
	private String customerKey;
	private String redEnvelopeIds;
	private String dishMenus;	
	private String redAmount;	

	public TCaterThirdorderinfo() {
	}

	public TCaterThirdorderinfo(Long id) {
		this.id = id;
	}

	public TCaterThirdorderinfo(Long id, String orderId,
			String channelNo, String channelName, String payStatus,
			String transactionId, String bankType, String bankBillno,
			BigDecimal amount, Timestamp createdAt, Timestamp updatedAt) {
		this.id = id;
		this.orderId = orderId;
		this.channelNo = channelNo;
		this.channelName = channelName;
		this.payStatus = payStatus;
		this.transactionId = transactionId;
		this.bankType = bankType;
		this.bankBillno = bankBillno;
		this.amount = amount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_STORE")
	@SequenceGenerator(name = "SEQ_STORE", sequenceName = "t_cater_thirdorderinfo_id_seq", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ORDER_ID", length = 32)
	public String getOrderId() {
		return this.orderId;
	}
	
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "THIRD_ORDER_ID", length = 32)
	public String getThirdOrderId() {
		return thirdOrderId;
	}

	public void setThirdOrderId(String thirdOrderId) {
		this.thirdOrderId = thirdOrderId;
	}

	@Column(name = "CHANNEL_NO", length = 32)
	public String getChannelNo() {
		return this.channelNo;
	}

	public void setChannelNo(String channelNo) {
		this.channelNo = channelNo;
	}

	@Column(name = "CHANNEL_NAME", length = 32)
	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	@Column(name = "PAY_STATUS", length = 2)
	public String getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	@Column(name = "TRANSACTION_ID", length = 64)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "BANK_TYPE", length = 32)
	public String getBankType() {
		return this.bankType;
	}

	public void setBankType(String bankType) {
		this.bankType = bankType;
	}

	@Column(name = "BANK_BILLNO", length = 64)
	public String getBankBillno() {
		return this.bankBillno;
	}

	public void setBankBillno(String bankBillno) {
		this.bankBillno = bankBillno;
	}

	@Column(name = "AMOUNT", precision = 8)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "CREATED_AT")
	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "UPDATED_AT")
	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "REFUND_NO", length = 32)
	public String getRefundNo() {
		return refundNo;
	}

	public void setRefundNo(String refundNo) {
		this.refundNo = refundNo;
	}

	@Column(name = "MERCHANT_NO", length = 62)
	public String getMerchantNo() {
		return merchantNo;
	}

	public void setMerchantNo(String merchantNo) {
		this.merchantNo = merchantNo;
	}
	
	@Column(name = "PAY_STORE_ID", length = 62)
	public String getPayStoreId() {
		return payStoreId;
	}

	public void setPayStoreId(String payStoreId) {
		this.payStoreId = payStoreId;
	}
	@Column(name = "PAY_STORE_NAME", length = 62)
	public String getPayStoreName() {
		return payStoreName;
	}

	public void setPayStoreName(String payStoreName) {
		this.payStoreName = payStoreName;
	}

	@Column(name = "CUSTOMERKEY", length = 64)
	public String getCustomerKey() {
		return customerKey;
	}

	public void setCustomerKey(String customerKey) {
		this.customerKey = customerKey;
	}

	@Column(name = "REDENVELOPEIDS", length = 200)
	public String getRedEnvelopeIds() {
		return redEnvelopeIds;
	}

	public void setRedEnvelopeIds(String redEnvelopeIds) {
		this.redEnvelopeIds = redEnvelopeIds;
	}
	@Column(name = "DISHMENUS")
	public String getDishMenus() {
		return dishMenus;
	}

	public void setDishMenus(String dishMenus) {
		this.dishMenus = dishMenus;
	}
	@Column(name = "REDAMOUNT", length =10)
	public String getRedAmount() {
		return redAmount;
	}

	public void setRedAmount(String redAmount) {
		this.redAmount = redAmount;
	}	
}
