package com.hi.pay.models;
// Generated 2013-8-22 16:59:56 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCaterOrdermaininfo generated by hbm2java
 */
@Entity
@Table(name="T_CATER_ORDERMAININFO"
)
public class TCaterOrdermaininfo  implements java.io.Serializable {


     private String orderid;
     private BigDecimal version;
     private String serialid;
     private String customerid;
     private String storeid;
     private String tableno;
     private String contactname;
     private String contactphone;
     private String sex;
     private Integer participantnumber;
     private Date dinningtime;
     private String deliveryaddressid;
     private BigDecimal distance;
     private String status;
     private Short potnumber;
     private String potstatus;
     private Short waiternumber;
     private String ordertype;
     private String deliverytype;
     private String recieptdept;
     private String paychannel;
     private String deliveryagent;
     private String potbillid;
     private String custmemo;
     private String agentmemo;
     private Timestamp orderTime;
     private String orderSrc;
     private String createdBy;
     private Timestamp createdDt;
     private String modifiedBy;
     private Timestamp modifiedDt;
     private String approvedBy;
     private Timestamp approvedDt;
     private String backupContactPhoneNum;
     private String memo;
     private String orderDinningTimeType;
     private String lockedBy;
     private Timestamp lockedDt;
     private String ordernature;
     private String discount;
     private String reservedTime;
     private String dinningType;
     private String createdName;
     private String modifiedName;
     private String approvedName;
     private String lockedName;
     private String paystatus;

    public TCaterOrdermaininfo() {
    }

	
    public TCaterOrdermaininfo(String orderid, String serialid) {
        this.orderid = orderid;
        this.serialid = serialid;
    }
    public TCaterOrdermaininfo(String orderid, String serialid, String customerid, String storeid, String tableno, String contactname, String contactphone, String sex, Integer participantnumber, Date dinningtime, String deliveryaddressid, BigDecimal distance, String status, Short potnumber, String potstatus, Short waiternumber, String ordertype, String deliverytype, String recieptdept, String paychannel, String deliveryagent, String potbillid, String custmemo, String agentmemo, Timestamp orderTime, String orderSrc, String createdBy, Timestamp createdDt, String modifiedBy, Timestamp modifiedDt, String approvedBy, Timestamp approvedDt, String backupContactPhoneNum, String memo, String orderDinningTimeType, String lockedBy, Timestamp lockedDt, String ordernature, String discount, String reservedTime, String dinningType, String createdName, String modifiedName, String approvedName, String lockedName) {
       this.orderid = orderid;
       this.serialid = serialid;
       this.customerid = customerid;
       this.storeid = storeid;
       this.tableno = tableno;
       this.contactname = contactname;
       this.contactphone = contactphone;
       this.sex = sex;
       this.participantnumber = participantnumber;
       this.dinningtime = dinningtime;
       this.deliveryaddressid = deliveryaddressid;
       this.distance = distance;
       this.status = status;
       this.potnumber = potnumber;
       this.potstatus = potstatus;
       this.waiternumber = waiternumber;
       this.ordertype = ordertype;
       this.deliverytype = deliverytype;
       this.recieptdept = recieptdept;
       this.paychannel = paychannel;
       this.deliveryagent = deliveryagent;
       this.potbillid = potbillid;
       this.custmemo = custmemo;
       this.agentmemo = agentmemo;
       this.orderTime = orderTime;
       this.orderSrc = orderSrc;
       this.createdBy = createdBy;
       this.createdDt = createdDt;
       this.modifiedBy = modifiedBy;
       this.modifiedDt = modifiedDt;
       this.approvedBy = approvedBy;
       this.approvedDt = approvedDt;
       this.backupContactPhoneNum = backupContactPhoneNum;
       this.memo = memo;
       this.orderDinningTimeType = orderDinningTimeType;
       this.lockedBy = lockedBy;
       this.lockedDt = lockedDt;
       this.ordernature = ordernature;
       this.discount = discount;
       this.reservedTime = reservedTime;
       this.dinningType = dinningType;
       this.createdName = createdName;
       this.modifiedName = modifiedName;
       this.approvedName = approvedName;
       this.lockedName = lockedName;
    }
   
     @Id 
    
    @Column(name="ORDERID", unique=true, nullable=false, length=32)
    public String getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }
    
    @Column(name="VERSION", precision=22, scale=0)
    public BigDecimal getVersion() {
        return this.version;
    }
    
    public void setVersion(BigDecimal version) {
        this.version = version;
    }
    
    @Column(name="SERIALID", nullable=false, length=50)
    public String getSerialid() {
        return this.serialid;
    }
    
    public void setSerialid(String serialid) {
        this.serialid = serialid;
    }
    
    @Column(name="CUSTOMERID", length=32)
    public String getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }
    
    @Column(name="STOREID", length=16)
    public String getStoreid() {
        return this.storeid;
    }
    
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }
    
    @Column(name="TABLENO", length=1024)
    public String getTableno() {
        return this.tableno;
    }
    
    public void setTableno(String tableno) {
        this.tableno = tableno;
    }
    
    @Column(name="CONTACTNAME", length=50)
    public String getContactname() {
        return this.contactname;
    }
    
    public void setContactname(String contactname) {
        this.contactname = contactname;
    }
    
    @Column(name="CONTACTPHONE", length=16)
    public String getContactphone() {
        return this.contactphone;
    }
    
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone;
    }
    
    @Column(name="SEX", length=2)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="PARTICIPANTNUMBER", precision=8, scale=0)
    public Integer getParticipantnumber() {
        return this.participantnumber;
    }
    
    public void setParticipantnumber(Integer participantnumber) {
        this.participantnumber = participantnumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DINNINGTIME", length=7)
    public Date getDinningtime() {
        return this.dinningtime;
    }
    
    public void setDinningtime(Date dinningtime) {
        this.dinningtime = dinningtime;
    }
    
    @Column(name="DELIVERYADDRESSID", length=16)
    public String getDeliveryaddressid() {
        return this.deliveryaddressid;
    }
    
    public void setDeliveryaddressid(String deliveryaddressid) {
        this.deliveryaddressid = deliveryaddressid;
    }
    
    @Column(name="DISTANCE", precision=8)
    public BigDecimal getDistance() {
        return this.distance;
    }
    
    public void setDistance(BigDecimal distance) {
        this.distance = distance;
    }
    
    @Column(name="STATUS", length=2)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="POTNUMBER", precision=4, scale=0)
    public Short getPotnumber() {
        return this.potnumber;
    }
    
    public void setPotnumber(Short potnumber) {
        this.potnumber = potnumber;
    }
    
    @Column(name="POTSTATUS", length=2)
    public String getPotstatus() {
        return this.potstatus;
    }
    
    public void setPotstatus(String potstatus) {
        this.potstatus = potstatus;
    }
    
    @Column(name="WAITERNUMBER", precision=4, scale=0)
    public Short getWaiternumber() {
        return this.waiternumber;
    }
    
    public void setWaiternumber(Short waiternumber) {
        this.waiternumber = waiternumber;
    }
    
    @Column(name="ORDERTYPE", length=2)
    public String getOrdertype() {
        return this.ordertype;
    }
    
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype;
    }
    
    @Column(name="DELIVERYTYPE", length=2)
    public String getDeliverytype() {
        return this.deliverytype;
    }
    
    public void setDeliverytype(String deliverytype) {
        this.deliverytype = deliverytype;
    }
    
    @Column(name="RECIEPTDEPT", length=100)
    public String getRecieptdept() {
        return this.recieptdept;
    }
    
    public void setRecieptdept(String recieptdept) {
        this.recieptdept = recieptdept;
    }
    
    @Column(name="PAYCHANNEL", length=2)
    public String getPaychannel() {
        return this.paychannel;
    }
    
    public void setPaychannel(String paychannel) {
        this.paychannel = paychannel;
    }
    
    @Column(name="DELIVERYAGENT", length=16)
    public String getDeliveryagent() {
        return this.deliveryagent;
    }
    
    public void setDeliveryagent(String deliveryagent) {
        this.deliveryagent = deliveryagent;
    }
    
    @Column(name="POTBILLID", length=32)
    public String getPotbillid() {
        return this.potbillid;
    }
    
    public void setPotbillid(String potbillid) {
        this.potbillid = potbillid;
    }
    
    @Column(name="CUSTMEMO", length=1024)
    public String getCustmemo() {
        return this.custmemo;
    }
    
    public void setCustmemo(String custmemo) {
        this.custmemo = custmemo;
    }
    
    @Column(name="AGENTMEMO", length=1024)
    public String getAgentmemo() {
        return this.agentmemo;
    }
    
    public void setAgentmemo(String agentmemo) {
        this.agentmemo = agentmemo;
    }
    
    @Column(name="ORDER_TIME")
    public Timestamp getOrderTime() {
        return this.orderTime;
    }
    
    public void setOrderTime(Timestamp orderTime) {
        this.orderTime = orderTime;
    }
    
    @Column(name="ORDER_SRC", length=2)
    public String getOrderSrc() {
        return this.orderSrc;
    }
    
    public void setOrderSrc(String orderSrc) {
        this.orderSrc = orderSrc;
    }
    
    @Column(name="CREATED_BY", length=32)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    
    @Column(name="CREATED_DT")
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }
    
    @Column(name="MODIFIED_BY", length=32)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    
    @Column(name="MODIFIED_DT")
    public Timestamp getModifiedDt() {
        return this.modifiedDt;
    }
    
    public void setModifiedDt(Timestamp modifiedDt) {
        this.modifiedDt = modifiedDt;
    }
    
    @Column(name="APPROVED_BY", length=32)
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }
    
    @Column(name="APPROVED_DT")
    public Timestamp getApprovedDt() {
        return this.approvedDt;
    }
    
    public void setApprovedDt(Timestamp approvedDt) {
        this.approvedDt = approvedDt;
    }
    
    @Column(name="BACKUP_CONTACT_PHONE_NUM", length=32)
    public String getBackupContactPhoneNum() {
        return this.backupContactPhoneNum;
    }
    
    public void setBackupContactPhoneNum(String backupContactPhoneNum) {
        this.backupContactPhoneNum = backupContactPhoneNum;
    }
    
    @Column(name="MEMO", length=1024)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    
    @Column(name="ORDER_DINNING_TIME_TYPE", length=2)
    public String getOrderDinningTimeType() {
        return this.orderDinningTimeType;
    }
    
    public void setOrderDinningTimeType(String orderDinningTimeType) {
        this.orderDinningTimeType = orderDinningTimeType;
    }
    
    @Column(name="LOCKED_BY", length=32)
    public String getLockedBy() {
        return this.lockedBy;
    }
    
    public void setLockedBy(String lockedBy) {
        this.lockedBy = lockedBy;
    }
    
    @Column(name="LOCKED_DT")
    public Timestamp getLockedDt() {
        return this.lockedDt;
    }
    
    public void setLockedDt(Timestamp lockedDt) {
        this.lockedDt = lockedDt;
    }
    
    @Column(name="ORDERNATURE", length=2)
    public String getOrdernature() {
        return this.ordernature;
    }
    
    public void setOrdernature(String ordernature) {
        this.ordernature = ordernature;
    }
    
    @Column(name="DISCOUNT", length=12)
    public String getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(String discount) {
        this.discount = discount;
    }
    
    @Column(name="RESERVED_TIME", length=3)
    public String getReservedTime() {
        return this.reservedTime;
    }
    
    public void setReservedTime(String reservedTime) {
        this.reservedTime = reservedTime;
    }
    
    @Column(name="DINNING_TYPE", length=16)
    public String getDinningType() {
        return this.dinningType;
    }
    
    public void setDinningType(String dinningType) {
        this.dinningType = dinningType;
    }
    
    @Column(name="CREATED_NAME", length=32)
    public String getCreatedName() {
        return this.createdName;
    }
    
    public void setCreatedName(String createdName) {
        this.createdName = createdName;
    }
    
    @Column(name="MODIFIED_NAME", length=32)
    public String getModifiedName() {
        return this.modifiedName;
    }
    
    public void setModifiedName(String modifiedName) {
        this.modifiedName = modifiedName;
    }
    
    @Column(name="APPROVED_NAME", length=32)
    public String getApprovedName() {
        return this.approvedName;
    }
    
    public void setApprovedName(String approvedName) {
        this.approvedName = approvedName;
    }
    
    @Column(name="LOCKED_NAME", length=32)
    public String getLockedName() {
        return this.lockedName;
    }
    
    public void setLockedName(String lockedName) {
        this.lockedName = lockedName;
    }

    @Column(name="PAYSTATUS", length=2)
	public String getPaystatus() {
		return paystatus;
	}

	public void setPaystatus(String paystatus) {
		this.paystatus = paystatus;
	}

}

